data_in_dir = "../../data/ori_data"
data_out_dir = "../../data/normal_data"
exp_name = "ace2005_lu"
task_type = "ee"
language = "en"
pretrained_model_path = "../../data/pretrained_models/bert-base-uncased"
ori_data_format = "tplinker"
add_char_span = False
ignore_subword_match = True
max_word_num = 50000 # the max size of word2id dict
min_word_freq = 3 # the minimum number of words in word2id
